### ISSUE TITLE
是否可以fork项目后自行开发？

### ISSUE THREAD

**Issue by championjing** [iHTCboy/iPomodoro-Flutter#2]
htc你好，看到项目很久没有更新，自己在使用过程中，想到一些优化的点，询问是否可以基于现在代码进行二次开发？

**Comment by iHTCboy** [comment]
> htc你好，看到项目很久没有更新，自己在使用过程中，想到一些优化的点，询问是否可以基于现在代码进行二次开发？

可以啊。如果可以，注明一下来源，谢谢~
